name: Build React Native App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    env:
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        cd ios && pod install

    - name: Decode keystore
      if: env.ANDROID_KEYSTORE_BASE64 != ''
      run: |
        echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/my-release-key.keystore

    - name: Configure signing
      if: env.ANDROID_KEYSTORE_BASE64 != ''
      run: |
        cd android && echo "storePassword=$KEYSTORE_PASSWORD" >> gradle.properties
        cd android && echo "keyPassword=$KEY_PASSWORD" >> gradle.properties
        cd android && echo "keyAlias=$KEY_ALIAS" >> gradle.properties
        cd android && echo "storeFile=my-release-key.keystore" >> app/build.gradle

    - name: Build Android
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Build iOS
      run: |
        cd ios
        xcodebuild -workspace YourProjectName.xcworkspace -scheme YourProjectName -configuration Release -sdk iphoneos -archivePath $PWD/build/YourProjectName.xcarchive archive
        xcodebuild -exportArchive -archivePath $PWD/build/YourProjectName.xcarchive -exportOptionsPlist $PWD/YourProjectName/Info.plist -exportPath $PWD/build/YourProjectName

    - name: Upload Android build artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-app
        path: android/app/build/outputs/apk/release/app-release.apk

    - name: Upload iOS build artifact
      uses: actions/upload-artifact@v2
      with:
        name: ios-app
        path: ios/build/YourProjectName.ipa
