name: Build React Native App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_android:
    runs-on: macos-latest

    env:
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Decode keystore
        if: env.ANDROID_KEYSTORE_BASE64 != ''
        run: |
          mkdir -p android/app
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/my-release-key.keystore

      - name: Configure signing
        if: env.ANDROID_KEYSTORE_BASE64 != ''
        run: |
          echo "storePassword=$KEYSTORE_PASSWORD" >> android/gradle.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/gradle.properties
          echo "keyAlias=$KEY_ALIAS" >> android/gradle.properties
          echo "storeFile=my-release-key.keystore" >> android/app/build.gradle

      - name: Set Gradlew permissions
        run: chmod +x android/gradlew

      - name: Build Android
        run: ./gradlew assembleRelease
        working-directory: android

      - name: Upload Android build artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-app
          path: android/app/build/outputs/apk/release/app-release.apk

  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios && pod install

      - name: Build iOS
        run: |
          xcodebuild -workspace YourProjectName.xcworkspace -scheme YourProjectName -configuration Release -sdk iphoneos -archivePath $PWD/build/YourProjectName.xcarchive archive
          xcodebuild -exportArchive -archivePath $PWD/build/YourProjectName.xcarchive -exportOptionsPlist $PWD/YourProjectName/Info.plist -exportPath $PWD/build/YourProjectName
        working-directory: ios

      - name: Upload iOS build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios-app
          path: ios/build/YourProjectName.ipa
